---
- hosts: localhost
  tasks:
    - ansible.builtin.set_fact:
        include_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - ansible.builtin.debug:
        var: include_roles
      tags:
        - always

    - ansible.builtin.include_role:
        apply:
          tags:
            - "{{ role_name }}"
        name: "{{ role_name }}"
      loop_control:
        loop_var: role_name
      with_items: "{{ include_roles }}"
      tags:
        - always