---
- community.general.homebrew:
    name: homebrew/cask/font-jetbrains-mono-nerd-font
    state: present

- ansible.builtin.copy:
    mode: "0644"
    src: hushlogin
    dest: "{{ ansible_user_dir }}/.hushlogin"
    force: true