---
- ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1

- ansible.builtin.git:
    repo: git@github.com:marlonrichert/zsh-autocomplete.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autocomplete
    depth: 1

- ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1

- community.general.homebrew:
    name: 
      - zoxide
      - eza
    state: present

- ansible.builtin.copy:
    mode: "0644"
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc"
    force: true