# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$php\
$golang\
$docker_context\
$aws\
$fill\ 
$cmd_duration\
$line_break\
$character
"""

[aws]
symbol = '󰅟 '
format = '[$symbol($profile )(\($region\) )]($style)'

[character]
format = '[\$](bold green) '

[cmd_duration]
format = 'took [$duration]($style)'
min_time = 0

[directory]
read_only = ' 󰌾'

[docker_context]
symbol = ' '
format = '[$symbol$context]($style) '

[fill]
symbol = ' '

[git_branch]
symbol = ' '

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[golang]
symbol = ' '
format = '[$symbol($version )]($style)'

[php]
symbol = ' '
format = '[$symbol($version )]($style)'