---
- community.general.homebrew:
    name: tmux
    state: present

- ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    depth: 1

- ansible.builtin.copy:
    mode: "0644"
    src: tmux.conf
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    force: true

- ansible.builtin.command:
    cmd: ~/.tmux/plugins/tpm/bin/install_plugins
  register: result
  changed_when: "'Installing' in result.stdout"

- ansible.builtin.command:
    cmd: ~/.tmux/plugins/tpm/bin/update_plugins all
  register: result
  changed_when: "'Fast-forward' in result.stdout"