---
- ansible.builtin.copy:
    mode: "0644"
    src: init.lua
    dest: "{{ ansible_user_dir }}/.config/nvim"
    force: true

- ansible.builtin.copy:
    mode: "0644"
    src: lua/
    dest: "{{ ansible_user_dir }}/.config/nvim/lua"
    force: true